### ISSUE TITLE
Incorrect message in Exception

### ISSUE THREAD

**Issue by egor-bogomolov** [JetBrains-Research/psiminer#13]
Hello, thanks for a great tool! On [this line](https://github.com/JetBrains-Research/psiminer/blob/psiminer_v2/psiminer-cli/src/main/kotlin/config/PsiTreeTransformationConfigs.kt#L57) the message in the exception should be "resolve types" not "remove comments.

**Comment by SpirinEgor** [comment]
Thanks! Will fix it in the next commit.
